---

name: Thalassa

channels:
  - conda-forge

dependencies:
  - python>=3.9
  - cartopy
  - datashader
  - fiona
  - geopandas
  - geos
  - geoviews
  - holoviews
  - numpy<1.24
  - pandas
  - shapely
  - xarray
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pymdown-extensions
