---

name: Thalassa

channels:
  - conda-forge

dependencies:
  - python=3.9
  - proj<8
  - datashader
  - panel
  - holoviews
  - geoviews
  - cartopy<0.20
  - shapely=1.7.1
  - ruamel.yaml
  - black=21.11b0
