---

site_name: "Thalassa"
use_directory_urls: false
repo_url: "https://github.com/ec-jrc/thalassa"

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"

nav:
  - Overview : index.md
  - Installation : installation.md
  - Development: development.md
  - API : api.md

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - toc:
      permalink: true

plugins:
  - "search"
  - "mkdocstrings":
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false
            show_root_members_full_path: false
