---

site_name: "Thalassa"
use_directory_urls: false
repo_url: "https://github.com/ec-jrc/thalassa"

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"

nav:
  - Overview : index.md
  - Installation : installation.md
  - Development: development.md
  - API : api.md

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - toc:
      permalink: true

watch:
  - "docs"
  - "thalassa"

plugins:
  - "search"
  - "mkdocstrings":
      default_handler: python
      handlers:
        python:
          options:
            # General
            allow_inspection: true
            show_source: false
            # Headings
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: true
            show_root_members_full_path: true
            # members
            members_order: "source"

            annotations_path: "brief"
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
            signature_crossrefs: true
            show_root_heading: true
