#!/bin/bash
set -xeuo pipefail

mkdir data

wget -O data/stations.csv "https://www.dropbox.com/s/q33b32kh37taohf/stations.csv?dl=1"
wget -O data/animation.mp4 "https://www.dropbox.com/s/bvva8qkpd3nlwox/animation.mp4?dl=1"
wget -O data/dataset.nc "https://www.dropbox.com/s/q2fu9vac682jgbi/dataset.nc?dl=1"
wget -O data/stations.zip "https://www.dropbox.com/s/avubjuz93gqwojl/stations.zip?dl=1"
wget -O data/thalassa.png "https://www.dropbox.com/s/nfpivybiyrb3p4g/thalassa.png?dl=1"


#https://github.com/psychemedia/jupyterserverproxy-openrefine
#python -m bash_kernel.install
#mkdir -p $HOME/.jupyter/
#mv .binder/jupyter_notebook_config.py $HOME/.jupyter/

#https://github.com/binder-examples/bokeh
#jupyter labextension install @jupyterlab/server-proxy
#jupyter serverextension enable --sys-prefix jupyter_server_proxy

# Install the bokeh server extension so that Bokeh launches at startup
#mv .binder/bokehserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# Enable Bokeh extension
#jupyter serverextension enable --sys-prefix bokehserverextension


#https://github.com/holoviz-demos/clifford
# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy
# install the panel server extension so that
# panel launches at startup
mv panelserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable panel extension
jupyter serverextension enable --sys-prefix panelserverextension

