#!/bin/bash
set -xeuo pipefail

mkdir data

#with dropbox
#wget -O data/stations.csv "?dl=1"
#wget -O data/animation.mp4 "https://www.dropbox.com/s/bvva8qkpd3nlwox/animation.mp4?dl=1"
#wget -O data/dataset.nc "https://www.dropbox.com/s/q2fu9vac682jgbi/dataset.nc?dl=1"
#wget -O data/stations.zip "https://www.dropbox.com/s/avubjuz93gqwojl/stations.zip?dl=1"
#wget -O data/thalassa.png "https://www.dropbox.com/s/nfpivybiyrb3p4g/thalassa.png?dl=1"



#from Google Drive using https://kobkrit.com/how-to-directly-download-files-from-dropbox-or-google-drive-using-wget-in-terminal-or-in-google-573168195011
pip install Gdown

cd data

gdown --id 12RA5YO66t59LbG1O-nFPEyYjAdr2YCd8
gdown --id 116Mhabb1PeOd27ZoATXQbA1eC6p31Llq
gdown --id 1IWgfahGebMSBPWYhtmuH-4w0BDVYwnTR
gdown --id 1xSfV7Ta7eIYU-lcdSgzpqLOvt_hWs_hL
gdown --id 1g6PsdqdTmZaODmTjlmoxMXcvZA6pjuRU

cd ..

#https://github.com/psychemedia/jupyterserverproxy-openrefine
#python -m bash_kernel.install
#mkdir -p $HOME/.jupyter/
#mv .binder/jupyter_notebook_config.py $HOME/.jupyter/

#https://github.com/binder-examples/bokeh
#jupyter labextension install @jupyterlab/server-proxy
#jupyter serverextension enable --sys-prefix jupyter_server_proxy

# Install the bokeh server extension so that Bokeh launches at startup
#mv .binder/bokehserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# Enable Bokeh extension
#jupyter serverextension enable --sys-prefix bokehserverextension


#https://github.com/holoviz-demos/clifford
# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy
# install the panel server extension so that
# panel launches at startup
mv .binder/panelserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable panel extension
jupyter serverextension enable --sys-prefix panelserverextension

