name: test

on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - '**.py'
      - '.github/workflows/*test*.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'requirements/requirements*.txt'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/*test*.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'requirements/requirements*.txt'

jobs:
  test:
    name: test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python: [ '3.9', '3.10', '3.11', '3.12']
        # include:
        #   - os: "macos-latest"
        #     python: "3.12"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@main
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}
      - uses: actions/cache@main
        id: cache-netcdfs
        with:
          path: |
            notebooks/schout_adcirc_20230828.nc
            notebooks/schout_adcirc_20230829.nc
            notebooks/schout_adcirc_20230830.nc
          key: test-stofs-3d-atl-netcdf-files
      - run: python --version
      - run: python -m pip install --upgrade pip
      - run: python -m pip --version
      - run: sudo apt-get install -y --no-install-recommends libgeos-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: python -m pip install -r requirements/requirements-dev.txt
      - run: python -m pip install ./
      - run: pytest --version
      - run: python -m pip cache info
      - run: mypy thalassa
      - run: make cov
      # We only run on a single matrix OS in order to speed up CI runtime
      - run: make exec_notebooks
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
